version: '3.3'
services:
  db:
    container_name: db
    build: ./database
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: awesome-links
      #- time zone?
    volumes:
      - ./database/data:/var/lib/postgresql/data